### ISSUE TITLE
Broken after updating from 2.0.22 to 2.1.2: jScrollPane is not a function (npm, webpack)

### ISSUE THREAD

**Issue by hheexx** [vitch/jScrollPane#356]
After updating looks like jScrollPane is not in bundle anymore

t(...).jScrollPane is not a function

Latest jQuery (3.3.1)
Latest Webpack (3.11.0)

Reverting to 2.0.22 fixes the problem. I tried multiple times.

**Comment by illuusio** [comment]
Ok. have to investigate in this ASAP

**Comment by illuusio** [comment]
And could you provide Webpack example how it's not working so I can test this

**Comment by hheexx** [comment]
Webpack config is preaty simple. Attached.
[webpack.config.js.zip](https://github.com/vitch/jScrollPane/files/1735848/webpack.config.js.zip)


What I forgot to mention is that I use Typescript.

jscrollpane is just imported like this:
import 'jscrollpane';

**Comment by illuusio** [comment]
Ok Typescript is not updated yet in official repo or are you using your own. I test and let you know how this goes.

**Comment by hheexx** [comment]
What do you mean?
I don't understand.

**Comment by illuusio** [comment]
I'm not very familiar with Typescript but I understood https://github.com/DefinitelyTyped/DefinitelyTyped contains Typescript defination.

**Comment by hheexx** [comment]
I am not using any definitions.
I am just importing your JS.

I am not sure I understand what you changed between 2.0 and 2.1, is you explain it little batter maybe I can figure it out.

I think it may be webpack related more then typescript related.

**Comment by illuusio** [comment]
I think I just mess up things ;). There is not much changes and I think it's grunt or something based. Package.json is also new.

**Comment by hheexx** [comment]
Ill try to narrow version range first

**Comment by hheexx** [comment]
oh 2.0.23 is not on npm so I can't  try that.

**Comment by illuusio** [comment]
Can you provide your package.json so I can check this out more easily

**Comment by hheexx** [comment]
```
{
  "version": "1.0.0",
  "name": "ASP.NET",
  "private": true,
  "devDependencies": {
    "@types/highcharts": "5.0.18",
    "@types/jquery": "3.3.0",
    "awesome-typescript-loader": "3.4.1",
    "css-loader": "0.28.9",
    "extract-text-webpack-plugin": "3.0.2",
    "file-loader": "1.1.6",
    "node-sass": "4.7.2",
    "postcss-loader": "2.1.0",
    "sass-loader": "6.0.6",
    "style-loader": "0.20.2",
    "typescript": "2.7.2",
    "url-loader": "0.6.2",
    "webpack": "3.11.0"
  },
  "dependencies": {
    "bootstrap": "3.3.7",
    "double-slider": "1.0.7",
    "highcharts": "6.0.7",
    "jquery": "3.3.1",
    "jquery-mousewheel": "3.1.13",
    "jscrollpane": "2.0.22",
    "raven-js": "3.22.3"
  }
}

```

**Comment by hheexx** [comment]
I can also provide you working and non wokring version of my site for some limited time.
It is best we could meet on some IM for that?

**Comment by illuusio** [comment]
I updated new version of jScrollPane with correct grunt usage version is 2.1.3-rc.1. Does it solve you problem. I think I just need this index.ts bundling code which doesn't work

**Comment by hheexx** [comment]
does not work :(

Same error. jScrollPane is not a function.

**Comment by illuusio** [comment]
Ok then I need minimal non-working example to nail this down

**Comment by hheexx** [comment]
[not-working-jscrollpane.zip](https://github.com/vitch/jScrollPane/files/1784935/not-working-jscrollpane.zip)

**Comment by illuusio** [comment]
Ok I do:
```
npm install --save-dev
node_modules/.bin/webpack
and get error:
[at-loader] Checking finished with 2 errors                                                                                                                           
Hash: 126c6eb7a6ad975ab116
Version: webpack 3.11.0
Time: 5433ms
        Asset    Size  Chunks                    Chunk Names
    bundle.js  328 kB       0  [emitted]  [big]  main
bundle.js.map  403 kB       0  [emitted]         main
  [66] ./index.ts 75 bytes {0} [built]
    + 106 hidden modules

ERROR in [at-loader] TS2688: Cannot find type definition file for 'jQuery'.

ERROR in [at-loader] ./index.ts:6:1 
    TS2304: Cannot find name '$'.
```
Am I doing something wrong with debug?

**Comment by hheexx** [comment]
just "npm install"

**Comment by illuusio** [comment]
Hmm.. after doing some research can't get it working. Which Nodejs are you using? My version is 6.

**Comment by hheexx** [comment]
node v8.9.4
npm v5.7.1

but it should not make a difference.


1) delete node_modules
2) npm install
3) .\node_modules\.bin\webpack

**Comment by illuusio** [comment]
Ah Windows/Linux problem. jQuery should be jquery and add import in index.ts now I can replicate problem.
Is this the same problem https://medium.com/@NetanelBasal/typescript-integrate-jquery-plugin-in-your-project-e28c6887d8dc

**Comment by hheexx** [comment]
I don't understand.
Everyting mentioned in this article is allready done.

jQuery is imported globally with ProvidePlugin in webpack config. Lines 36-39.
Your plugin is declared to typescript in file iface.d.ts

I don't see this article referencing any linux/windows problem...

**Comment by illuusio** [comment]
What I mean is that Windows is more liberal with letter are they uppercase or not but what tried to say I get webpack working ok and testing it.

**Comment by hheexx** [comment]
aha.. cool.

**Comment by illuusio** [comment]
Ok my bad! I'm so :-1: with npm and doesn't understand how it really works. Still learning though. Problem is *node_modules/jscrollpane/package.json* line:
`"main": "Gruntfile.js",`
and manually change it to:
`"main": "script/jquery.jscrollpane.min.js",`
It should work as expected. If you try this and I try to figure out how many other will rip of their pants if I make that change.

**Comment by hheexx** [comment]
Yup, that fixed it for me.
Update package please.

**Comment by illuusio** [comment]
Ok new RC made so test if it fix your problem and then close bug

**Comment by hheexx** [comment]
Fixed. 

Thanks!
